name: run-django-server

on:
  push:
    branches:
      - main

jobs:
  run_server:
    name: Run Django Server
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d
          sleep 10  # Wait for the containers to start
          curl http://localhost:8000  # Test if the server is running

      - name: Stop Docker containers
        run: docker-compose down